#!/usr/bin/bash

get_config() {
	FASTFETCH_CONFIG_FILE="${FASTFETCH_CONFIG_FILE:-/etc/greatlem0n-os/fastfetch.json}"
	QUERY="$1"
	FALLBACK="$2"
	shift
	shift
	OUTPUT="$(jq -r "$QUERY" "$FASTFETCH_CONFIG_FILE" 2>/dev/null || echo "$FALLBACK")"
	if [ "$OUTPUT" == "null" ] ; then
		echo "$FALLBACK"
		return
	fi
	echo "$OUTPUT"
}

DEFAULT_THEME="$(get_config '."default-theme"' "slate")"
FASTFETCH_CONFIG="$(get_config '."fastfetch-config"' "/usr/share/greatlem0n-os/fastfetch.jsonc")"
SHUFFLE_LOGO="$(get_config '."shuffle-logo"' "false")"
LOGO_DIRECTORY="$(get_config '."logo-directory"' "/usr/share/greatlem0n-os/fastfetch")"

if [ "$SHUFFLE_LOGO" == "true" ] ; then
  FETCH_LOGO="$(/usr/bin/find "$LOGO_DIRECTORY" -type f | /usr/bin/shuf -n 1)"
  /usr/bin/fastfetch --logo "$FETCH_LOGO" --color "$(/usr/libexec/greatlem0n-bling-fastfetch)" --config "$FASTFETCH_CONFIG" "$@"
else
  /usr/bin/fastfetch --color "$(/usr/libexec/greatlem0n-bling-fastfetch)" --config "$FASTFETCH_CONFIG" "$@"
fi


